// actions related to the app
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'

// actions related to community
export const SELECT_LOCAL = 'SELECT_LOCAL'

// actions related to styling
export const CHANGE_CARD_STYLE = 'CHANGE_CARD_STYLE'

// actions related to search
export const FOUND_BUILDINGS = 'FOUND_BUILDINGS'
export const FILTERED_BUILDINGS = 'FILTERED_BUILDINGS'
export const FOUND_SUBLETS = 'FOUND_SUBLETS'
export const FILTERED_SUBLETS = 'FILTERED_SUBLETS'
export const SELECT_PIN = 'SELECT_PIN'
export const SELECT_CORPORATION = 'SELECT_CORPORATION'
export const CHANGE_RENT_TYPE = 'CHANGE_RENT_TYPE'
export const SAVE_LEASE_FILTER_PARAMS = 'SAVE_LEASE_FILTER_PARAMS'
export const SAVE_SUBLET_FILTER_PARAMS = 'SAVE_SUBLET_FILTER_PARAMS'
export const SET_CURRENT_GPS_CENTER = 'SET_CURRENT_GPS_CENTER'
export const UPDATE_SEARCH_RADIUS = 'UPDATE_SEARCH_RADIUS'
export const TOGGLE_HIDE_SOLD_OUTS = 'TOGGLE_HIDE_SOLD_OUTS'
export const SORTED_BUILDINGS = 'SORTED_BUILDINGS'

// actions related to auth
export const AUTHENTICATE_TENANT = 'AUTHENTICATE_TENANT'
export const LOGOUT_TENANT = 'LOGOUT_TENANT'
export const FORCE_SIGNIN = 'FORCE_SIGNIN'
export const LOCATION_FORWARDING = 'LOCATION_FORWARDING'
export const FINGERPRINT_BROWSER = 'FINGERPRINT_BROWSER'
export const FORCE_SIGNIN_FAVORITE = 'FORCE_SIGNIN_FAVORITE'

// actions related to selections
export const SELECT_BUILDING = 'SELECT_BUILDING'
export const SEARCH_STRING = 'SEARCH_STRING'
export const CHANGE_SEARCH_STYLE = 'CHANGE_SEARCH_STYLE'
export const SELECT_POPUP_BUILDING = 'SELECT_POPUP_BUILDING'
export const NAV_TOP_TITLE = 'NAV_TOP_TITLE'
export const NAV_BOTTOM_TITLE = 'NAV_BOTTOM_TITLE'

// Actions related to messaging
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const SELECT_THREAD = 'SELECT_THREAD'
export const REQUEST_NOTIFICATIONS_PERMISSION = 'REQUEST_NOTIFICATIONS_PERMISSION'
export const CHAT_HELP = 'CHAT_HELP'
// export const LISTEN_TO_FIREBASE_DB = 'LISTEN_TO_FIREBASE_DB'
export const ADD_ALL_MESSAGES = 'ADD_ALL_MESSAGES'
export const MARK_AS_READ = 'MARK_AS_READ'
export const ADD_TOAST = 'ADD_TOAST'
export const REMOVE_TOAST = 'REMOVE_TOAST'

// Actions related to collecting intel
export const COLLECT_INTEL = 'COLLECT_INTEL'
export const CLEAR_INTEL_LIST = 'CLEAR_INTEL_LIST'
export const SAVE_INTEL_TO_CLOUD = 'SAVE_INTEL_TO_CLOUD'

// actions related to contract applications
export const I_APPLIED = 'I_APPLIED'
export const APPLIED_TO_ME = 'APPLIED_TO_ME'
export const APPLIED_LEASES = 'APPLIED_LEASES'
export const APPLY_FOR_THIS_BUILDING = 'APPLY_FOR_THIS_BUILDING'

// actions related to group applications
export const GROUP_MEMBERS = 'GROUP_MEMBERS'
export const MY_LEASE_APPLICATION = 'MY_LEASE_APPLICATION'
export const MY_APPLIED_BUILDING = 'MY_APPLIED_BUILDING'
