
export const BUILDING_INTERACTIONS = 'BUILDING_INTERACTIONS'
export const SUITE_INTERACTIONS = 'SUITE_INTERACTIONS'
export const USER_PREFERENCES = 'USER_PREFERENCES'
export const CHAT_LOGS = 'CHAT_LOGS'
export const CRM_ACTIVITY = 'CRM_ACTIVITY'
